name: Bygg og publiser docker-image for master

on:
  push:
    branches:
      - master
    paths-ignore:
      - .github/workflows/**

jobs:
  build-and-publish-on-master:
    runs-on: ubuntu-latest
    steps:

      - name: Sjekk ut koden
        uses: actions/checkout@v2

      - name: Sjekk om prodsetting er mulig
        run: echo "::set-env name=PROD_SBS_VARS_TEMPLATE_DEFINED::$([[ -f nais/prod-sbs/default.json ]] && echo 'true' || echo 'false')"

      - name: Test
        if: env.PROD_SBS_VARS_TEMPLATE_DEFINED == 'true'
        run: echo "Running deploy"
